### ISSUE TITLE
Add downloads tab

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/parallaxinc.github.io#5]
Add a downloads tab that will allow users to download content. I am not sure what is in store for this website, so I cannot be any more specific on what "content" needs to be included.

**Comment by bweir** [comment]
This is already available. Look at the PropellerIDE project page.

**Comment by DarkmatterVale** [comment]
Oh, ok. I was thinking about a downloads tab on the main website that held downloads for other content that is related. Maybe this is not needed?
